"""empty message

Revision ID: 16232e49311a
Revises: 0409c118946a
Create Date: 2025-04-11 14:36:16.715544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16232e49311a'
down_revision = '0409c118946a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_constraint('quote__daily_date_key', type_='unique')
        batch_op.drop_column('_daily_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_daily_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('quote__daily_date_key', ['_daily_date'])

    # ### end Alembic commands ###
