"""add daily columns to userstats

Revision ID: 2677feefef63
Revises: 0f2e24ba2bcc
Create Date: 2025-03-24 16:11:16.876738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2677feefef63'
down_revision = '0f2e24ba2bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_daily_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_daily_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_daily_completed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_daily_completed_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_column('last_daily_completed_date')
        batch_op.drop_column('total_daily_completed')
        batch_op.drop_column('max_daily_streak')
        batch_op.drop_column('current_daily_streak')

    # ### end Alembic commands ###
