"""Add unsubscribe token to User model

Revision ID: 28d3281a1ffb
Revises: generate_unsubscribe_tokens
Create Date: 2025-04-22 13:06:37.232313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d3281a1ffb'
down_revision = 'generate_unsubscribe_tokens'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unsubscribe_token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['unsubscribe_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('unsubscribe_token')

    # ### end Alembic commands ###
