"""Add incorrect_guesses column to game state tables

Revision ID: 53f9ed7981ee
Revises: 
Create Date: 2025-04-18 06:19:22.141567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f9ed7981ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_game_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incorrect_guesses', sa.JSON(), nullable=True))

    with op.batch_alter_table('anonymous_game_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incorrect_guesses', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anonymous_game_state', schema=None) as batch_op:
        batch_op.drop_column('incorrect_guesses')

    with op.batch_alter_table('active_game_state', schema=None) as batch_op:
        batch_op.drop_column('incorrect_guesses')

    # ### end Alembic commands ###
