"""empty message

Revision ID: d913c47be017
Revises: eccdc21c4b8b
Create Date: 2025-06-09 10:58:44.922894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd913c47be017'
down_revision = 'eccdc21c4b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_boost_multiplier', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('xp_boost_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('xp_boost_expires')
        batch_op.drop_column('xp_boost_multiplier')

    # ### end Alembic commands ###
