"""empty message

Revision ID: eccdc21c4b8b
Revises: 0224f33339a4
Create Date: 2025-06-04 11:29:07.656121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccdc21c4b8b'
down_revision = '0224f33339a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apple_user_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['apple_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('apple_user_id')

    # ### end Alembic commands ###
