"""fix daily_date column

Revision ID: f95313a1571c
Revises: 16232e49311a
Create Date: 2025-04-11 14:51:10.997702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95313a1571c'
down_revision = '16232e49311a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_date', sa.Date(), nullable=True))
        batch_op.create_unique_constraint(None, ['daily_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('daily_date')

    # ### end Alembic commands ###
